//go:build windows
// +build windows

package excel2pdf

import (
	"errors"
	"log/slog"
)

var ErrExcelOrLibreOfficeNotInstalled = errors.New("neither Microsoft Excel nor LibreOffice is installed on this system")

func convertExcelToPdf(excelFile string) (pdfFile string, err error) {
	libreOfficePath, err := findLibreOfficeBinPath()
	if err != nil {
		return "", err
	}
	if libreOfficePath != "" {
		pdfFile, err = convertExcelToPDFWithLibreOffice(excelFile)
		if err == nil {
			slog.Info("PDF successfully generated by LibreOffice", "file", pdfFile)
		}
		return pdfFile, err
	}

	ok, err := isExcelInstalled()
	if err != nil {
		return "", err
	}
	if ok {
		pdfFile, err = convertExcelToPDFWithExcel(excelFile)
		if err == nil {
			slog.Info("PDF successfully generated by Microsoft Excel", "file", pdfFile)
		}
		return pdfFile, err
	}
	return "", ErrExcelOrLibreOfficeNotInstalled
}
